defaults:
  - environ: default
  - _self_

transform_resize: 224

train_ratio: 0.7

batch_size: 32

out_features: 2
learning_rate: 0.001
epochs: 100

model: "convnext"

checkpoint_save_path: "./model"
